#!/usr/bin/env sh

if [ "_$RANDOMIZE_PASSWORD" = "_1" ]; then
    ROOT_PASSWORD=`pwgen -c -n -1 12`
    echo Password: $ROOT_PASSWORD
    echo "root:$ROOT_PASSWORD" | chpasswd
fi

if [ ! -f $VMAIL_DIR/authdb.sqlite ]; then
    chown $VMAIL_USER:$VMAIL_GROUP $VMAIL_DIR
    chmod 770 $VMAIL_DIR
    /usr/local/vimbadmin/bin/doctrine-cli.php create-tables
    chown $VMAIL_USER:$VMAIL_GROUP $VMAIL_DIR/authdb.sqlite
    chmod 660 $VMAIL_DIR/authdb.sqlite
fi

/usr/sbin/dovecot -c /etc/dovecot/dovecot.conf
service php5-fpm start
service nginx start

exec /usr/sbin/sshd -D
