#!/usr/bin/env sh

if [ "_$RANDOMIZE_PASSWORD" = "_1" ]; then
    ROOT_PASSWORD=`pwgen -c -n -1 12`
    echo Password: $ROOT_PASSWORD
    echo "root:$ROOT_PASSWORD" | chpasswd
fi

if [ ! -f $VMAIL_DIR/authdb.sqlite ]; then
    chown $VMAIL_USER:$VMAIL_GROUP $VMAIL_DIR
    chmod 770 $VMAIL_DIR
    /usr/local/vimbadmin/bin/doctrine-cli.php create-tables
    chown $VMAIL_USER:$VMAIL_GROUP $VMAIL_DIR/authdb.sqlite
    chmod 660 $VMAIL_DIR/authdb.sqlite
fi

echo "127.0.0.1 $(hostname) $(hostname -s)" >> /etc/hosts

/usr/sbin/dovecot -c /etc/dovecot/dovecot.conf
service php5-fpm start
service nginx start

# The SSH init that we'll not be using would've created that directory.
test -d /var/run/sshd || mkdir -p -m0755 /var/run/sshd
exec /usr/sbin/sshd -D
